"""Bonus mini-product UI — Lab 17 memory agent demo (STUDENT starter).

Full +10 (live demo) when ALL of these work:

1. Load test cases from `data/sessions.json` (public). Golden file optional.
2. Pick a case; UI shows query, expected layer, user_id, thread_id.
3. Run student memory retrieval and show per-layer evidence + merged context.
4. Chat box continues as that user/thread: append turns, retrieve again, keep
   history, and the assistant reply is generated by OpenAI grounded in the
   retrieved memory context (gpt-4o-mini by default).

The page shell, budget metrics, OpenAI chat, and layered retrieval are wired for
the completed bonus demo.

Run:

    docker compose run --rm --service-ports app \\
      streamlit run src/demo_ui.py --server.address 0.0.0.0 --server.port 8501

or locally:  streamlit run src/demo_ui.py
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import streamlit as st

from src.config import settings
from src.llm import generate_reply, openai_available
from src.memory_student import StudentMemory
from src.short_term import ShortTermMemory
from src.utils import GOLDEN_PATH, load_dataset, load_json
from src.zep_common import get_zep_client

LAYER_COLORS = {
    "short_term": "#2563eb",
    "long_term": "#059669",
    "episodic": "#d97706",
    "semantic": "#7c3aed",
}

CSS = """
<style>
.block-container { padding-top: 2rem; max-width: 1200px; }
.lab-badge {
    display:inline-block; padding:2px 10px; border-radius:999px;
    color:#fff; font-size:0.75rem; font-weight:600; letter-spacing:.02em;
    margin-right:6px;
}
.lab-card {
    border:1px solid rgba(128,128,128,.25); border-radius:12px;
    padding:14px 16px; margin-bottom:12px; background:rgba(127,127,127,.06);
}
.lab-kv { font-size:0.85rem; opacity:.85; }
.lab-kv b { opacity:1; }
.stChatMessage { border-radius:12px; }
</style>
"""


def load_cases() -> list[dict[str, Any]]:
    cases = list(load_dataset()["evaluations"])
    if GOLDEN_PATH.exists():
        try:
            cases.extend(load_json(GOLDEN_PATH).get("evaluations") or [])
        except Exception:
            pass
    return cases


def format_case(case: dict[str, Any]) -> str:
    return f"{case['id']} · {case['expected_layer']} · {case['user_id']}"


def layer_badge(layer: str) -> str:
    color = LAYER_COLORS.get(layer, "#475569")
    return f'<span class="lab-badge" style="background:{color}">{layer}</span>'


def retrieve_for_case(
    memory: StudentMemory,
    case: dict[str, Any],
    extra_messages: list[dict[str, str]],
) -> dict[str, Any]:
    """Run student retrieval for the loaded case.

    Return a dict with keys:
      - "merged_context": str  (StudentMemory.assemble_context output)
      - "layers": dict[str, str]  (per-layer evidence: short_term/long_term/
                                   episodic/semantic)
      - "budget": dict  (the breakdown from assemble_context)

    Hints:
      * Build short_term from case["fixture_messages"] if present, else from
        the matching user/thread messages in data/sessions.json, plus
        extra_messages. E01 has no fixture — it uses thread minh-s1.
      * Decide which durable layers to fetch from case["expected_layer"] (or
        case["retrieve_layers"] for "mixed"), then call
        memory.retrieve_long_term / retrieve_episodic / retrieve_semantic.
      * Keep user_id and thread_id from the loaded case.
      * Finish with memory.assemble_context(layers).
    """
    layers = {
        "short_term": "",
        "long_term": "",
        "episodic": "",
        "semantic": "",
    }

    dataset = load_dataset()
    base_messages = case.get("fixture_messages")
    if base_messages is None:
        base_messages = []
        for user in dataset.get("users", []):
            if user.get("user_id") != case["user_id"]:
                continue
            for session in user.get("sessions", []):
                if session.get("thread_id") == case["thread_id"]:
                    base_messages = session.get("messages", [])
                    break
            break

    short_term = ShortTermMemory(
        strategy="sliding",
        max_recent_messages=6,
        pressure_tokens=450,
    )
    for message in [*base_messages, *extra_messages]:
        short_term.add(message["role"], message["content"])
    layers["short_term"] = short_term.render()

    expected_layer = case.get("expected_layer", "")
    if expected_layer == "mixed":
        durable_layers = case.get("retrieve_layers") or ["long_term", "semantic"]
    elif expected_layer in {"long_term", "episodic", "semantic"}:
        durable_layers = [expected_layer]
    else:
        durable_layers = []

    query = case["query"]
    if "long_term" in durable_layers:
        layers["long_term"] = memory.retrieve_long_term(
            case["user_id"], case["thread_id"], query
        )
    if "episodic" in durable_layers:
        layers["episodic"] = memory.retrieve_episodic(case["user_id"], query)
    if "semantic" in durable_layers:
        layers["semantic"] = memory.retrieve_semantic(settings.semantic_graph_id, query)

    merged_context, budget = memory.assemble_context(layers)
    return {
        "merged_context": merged_context,
        "layers": layers,
        "budget": budget,
    }


def main() -> None:
    st.set_page_config(page_title="Lab 17 Memory Demo", page_icon="🧠", layout="wide")
    st.markdown(CSS, unsafe_allow_html=True)
    st.title("🧠 Lab 17 — Memory Agent Demo")
    st.caption("Load a test case, inspect layered retrieval, then keep chatting as that user.")

    with st.sidebar:
        st.header("⚙️ Setup")
        zep_ok = bool(settings.zep_api_key)
        st.markdown(("✅" if zep_ok else "⚠️") + " Zep API key "
                    + ("configured" if zep_ok else "missing"))
        st.markdown(("✅" if openai_available() else "⚠️") + " OpenAI key "
                    + ("configured" if openai_available() else "missing"))
        st.caption(f"Chat model: `{settings.openai_model}`")
        st.divider()

        cases = load_cases()
        if not cases:
            st.error("No evaluation cases found.")
            return
        labels = [format_case(c) for c in cases]
        chosen = st.selectbox("Test case", labels)
        case = cases[labels.index(chosen)]

    st.markdown(
        f'<div class="lab-card">{layer_badge(case.get("expected_layer","?"))}'
        f'<b>{case["id"]}</b><br>'
        f'<span class="lab-kv"><b>User:</b> {case.get("user_id","-")} &nbsp;·&nbsp; '
        f'<b>Thread:</b> {case.get("thread_id","-")}</span>'
        f'<p style="margin:.5rem 0 0">{case.get("query","")}</p>'
        f'<span class="lab-kv">{case.get("description","")}</span></div>',
        unsafe_allow_html=True,
    )

    if st.session_state.get("case_id") != case["id"]:
        st.session_state.case_id = case["id"]
        st.session_state.chat = []
        st.session_state.pop("last_result", None)

    col_run, _ = st.columns([1, 3])
    if col_run.button("▶️ Run retrieval on this case", use_container_width=True):
        try:
            memory = StudentMemory(get_zep_client())
            st.session_state.last_result = retrieve_for_case(memory, case, st.session_state.chat)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)

    result = st.session_state.get("last_result")
    if result:
        st.markdown("### 🔎 Retrieved context")
        active = [k for k, v in result["layers"].items() if v.strip()]
        st.markdown(" ".join(layer_badge(k) for k in active) or "_(nothing retrieved)_",
                    unsafe_allow_html=True)

        if result.get("budget"):
            cols = st.columns(4)
            for i, layer in enumerate(("short_term", "long_term", "episodic", "semantic")):
                b = result["budget"].get(layer, {})
                cols[i].metric(
                    layer,
                    f"{b.get('used_tokens', 0)} tok",
                    help=f"limit {b.get('limit_tokens', 0)} · raw {b.get('raw_tokens', 0)}",
                )

        with st.expander("Merged context (budget-trimmed)", expanded=True):
            st.code(result.get("merged_context") or "(empty)", language="markdown")
        for name, text in result["layers"].items():
            if text.strip():
                with st.expander(f"{name} evidence"):
                    st.write(text)

    st.markdown("### 💬 Continue chat as this user")
    for msg in st.session_state.get("chat", []):
        with st.chat_message(msg["role"]):
            st.write(msg["content"])

    prompt = st.chat_input("Message as this user…")
    if prompt:
        st.session_state.chat.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.write(prompt)
        try:
            memory = StudentMemory(get_zep_client())
            follow = retrieve_for_case(memory, {**case, "query": prompt}, st.session_state.chat)
            st.session_state.last_result = follow
            context = follow.get("merged_context", "")
            if openai_available():
                reply = generate_reply(context, st.session_state.chat[:-1], prompt)
            else:
                reply = ("_(OpenAI key missing — showing retrieved context instead)_\n\n"
                         + (context[:1500] or "(no memory retrieved)"))
            st.session_state.chat.append({"role": "assistant", "content": reply})
            with st.chat_message("assistant"):
                st.write(reply)
        except Exception as exc:  # noqa: BLE001
            st.exception(exc)


if __name__ == "__main__":
    main()
